=encoding UTF-8

=head1 NAME

OpenResty::Spec::Arch_cn - OpenSearch 体系结构白皮书（草案）

=head1 AUTHOR

Ting (于霆) <yuting@yahoo.cn>

=head1 VERSION

    CREATED:       Dec 1, 2007
    LAST MODIFIED: Dec 1, 2007
    VERSION:       0.01

=head1 DESCRIPTION

本文定义了 OpenSearch 的系统结构, 协议层由 OpenResty 支撑, 存储上使用的是PostgreSQL集群.

=head2 DESIGN GOALS

=over

=item *

能够支持 OpenResty 中对数据的所有操作, 在保证 OpenResty 的足够灵活的基础上，同时通过PostgreSQL
的存储过程，或者视图来简化 OpenResty 对于OpenSearch的复杂操作逻辑.

=item *

OpenSearch 结构化数据存储和查询部分是完全由 PostgreSQL 支持的. 非结构化数据是由某种分布式
文件系统来支撑. (这里的非结构化数据，通常是指大对象文件).

=item *

在存储结构化数据的时候,要保证灵活. 具体体现在可以支持用户自定义的数据结构.

=item *

系统本身要是可扩充的,每个用户拥有其各自的独立空间,用户在系统内部是可迁移的(在节点之间是可迁移.)

=back

=head2 DESIGN BACKGROUND

PE Team 长期对于理想Search系统的孜孜不倦的追求.  这个理想的系统具备的特征是, 高度可扩展的,支持丰富索引类型的,数据之间在系统内部可以建立关系的,容易运维的系统.

=head1 Data stream

=head1 System operate type.

=head1 User define.

=head1 Role define.

=head1 ACL

