#!/usr/bin/env perl

use strict;
use warnings;

use lib '../../lib';
use utf8;
use JSON::XS;
use YAML 'Dump';
use WWW::OpenResty::Simple;
#use Date::Manip;
use Getopt::Std;

my %opts;
getopts('u:s:p:h', \%opts);
if ($opts{h}) {
    die "Usage: $0 -u <user> -p <password> -s <openresty_server>\n";
}
my $user = $opts{u} or
    die "No OpenResty account name specified via option -u\n";
my $password = $opts{p} or
    die "No OpenResty account's Admin password specified via option -p\n";
my $server = $opts{s} || 'http://api.openresty.org';

my $resty = WWW::OpenResty::Simple->new( { server => $server } );
$resty->login($user, $password);
$resty->delete("/=/role/Public/~/~");
#$resty->delete("/=/role");
$resty->delete("/=/view");
$resty->delete("/=/feed");
$resty->delete("/=/model");

$resty->post(
    '/=/model/Menu',
    {
        description => "Site menus",
        columns => [
            { name => 'name', type => 'ltree', label => 'Menu name (anchor)' },
            { name => 'label', type => 'text', label => 'Menu label' },
            { name => 'content', type => 'text', label => 'Menu content' },
            { name => 'display_order', type => 'smallint', label => 'Menu content', default => 0 },
        ],
    }
);

$resty->post(
    '/=/model/Menu/~/~',
    [

        { name => 'home.howdy', label => 'Howdy!', content => <<'_EOC_' },
I<Howdy>, nina!

My blog is here:

L<http://blog.agentzh.org>

=begin html

<p> <I>This</I> is <b><font color="red">plain HTML</font></b> </p>

<center>
<table width="100%" border="1">
    <tr><td>Cat</td><td>Dog</td></tr>
    <tr><td>Monkey</td><td>Banana</td></tr>
    <tr><td>Yahoo</td><td>Google</td></tr>
</table>
</center>

=end html

_EOC_
        { name => "home", label => "Home", content => <<"_EOC_" },
=image gate.jpg

Private equity managers today see opportunities in vast sectors of the PRC economy that have no dominant industry leader, and in research labs that are percolating with innovations. China is one of the hottest for private equity investment.

We are proud that we are in China, we are with Chinese during this China age. It's honorable to contribute in China's private equity industry development and help Chinese enterprises in each steps of their growths. We are looking forward to meet entrepreneurs, professionals,and bankers through this website. 
Private equity managers today see opportunities in vast sectors of the PRC economy that have no dominant industry leader, and in research labs that are percolating with innovations. China is one of the hottest for private equity investment.

=head3 What We Do

ON Capital is a China focused opportunity fund, dedicated in minority investments in high growth Chinese companies seeking expansion/development capital.

Since inception in year 2004, ON Capital has invested in various industries with 3 IPOs in Hong Kong, Australia and United States, and achieve 4times of return to all investors.

ON Capital is aiming to create values to investors, and is focusing in opportunity investment in China Mainland.  ON Capital believes  that China offers an attractive environment for investing in unlisted companies for, inter alia, because of China's macro economy growth and government institutional reforms. We regards the consolidation and restructuring of enterprises in both the private and state owned sectors is providing new investment opportunities. And current China’s tightened monetary policy is generally favorable for Private Equity activities with increasing investment opportunities
_EOC_
        { name => "portfolio", label => "Portfolio", content => <<"_EOC_" },
=head3 We have

=over

=item *

8 investments since 2004

=item *

106.6% Gross IRR

=item *

4.0x multiple to cost and all shareholder have received investment principal distribution in multiple

=item *

Investments crystallized via IPOs (HKSE, ASX, NYSE) generating a realized IRR of 129.1%

=back

=head3 Turbo Speed (HKSE:0818.HK)

=over

=item *

Awarded by China Mobile to be the sole provider of its nationwide Interactive Voice Response “IVR” platform to all service and content providers seeking to be connected to China Mobile

=item *

Now a subsidiary of Hi Sun Group Limited (HKSE: 0818.HK), which is listed on the Hong Kong Stock Exchange

=item *

Hi Sun has been operating the platform since late 2003 profitably and receives 15% of all revenue generated by users of all services on it (payment made by China Mobile directly)

=item *

While Hi Sun covers the whole nation, all competitors operate at only regional level, on a province by province basis

=item *

As IVR continue to grow in China, Hi Sun has huge operating leverage to expand into the rest of the mobile value-added service industry, based on comparison with the Korea and Japan markets

=item *

ON Capital led first round funding for 16% equity of Hi Sun and has disposed all of the stake at 7.3X multiple return

=back

=head3 Arasor (ASX:ARR)

=over

=item *

Founded and managed by Dr Simon Cao, a scientist in opto-electronics and labeled by Forbes as 'Godfather of WDM’

=item *

Mr Cao has personally funded Arasor with USD10mil+; and was previously the founder and key executive of Avanex and Oplink

=item *

Solid order book from 1st tier global telecom carriers and equipment vendors, with exceptionally strong growth in India and China

=item *

Proprietary technology platform which leads to significant cost and performance advantages

=item *

Arasor is currently the only company in the industry which has productized an optical chip set for Laser TV. As a new class of high-end consumer product, Laser TV has been well endorsed and signed up by a number of global consumer electronic giants such as Mitsubishi and Samsung

=item *

ON Capital led in early 2006 and gained 8.8% equity of Arasor

=item *

IPO in Oct 2006 at ASX at around 2X of ON Capital entry cost (with 2 years lock-up)

=back

=head3 Gushan (NYSE:GU)

=over

=item *

Known largest producer of Biodiesel in China having influence on government’s effort in promoting alternative or green fuel and in setting up a national standards and specifications of BioDiesel

=item *

Low competition with early mover advantage (Founded in 2001)

=item *

Currently an aggregate annual production capacity of 240,000 tons of biodiesel; strong revenue growth

=item *

In-house R&D team with proprietary technologies & IP rights

=item *

China being a big energy user, huge demand on diesel. With the ever-growing concern over crude oil price and supply, alternative fuel will continue to attract more attention

=item *

Gushan went IPO in December 2007 in NYSE (GU), ON Capital realized an IRR of 215% against our investment cost

=back
_EOC_
        { name => 'team.red', label => 'Red team', content => <<'_EOC_' },
Well, I have no idea B<what> you're C<talking about>...hoho...
_EOC_

        { name => 'team.cache', label => 'OpenResty::Cache', content => <<'_EOC_' },
=head1 NAME

OpenResty::Cache - Cache for OpenResty

=head1 SYNOPSIS

    use OpenResty::Config;
    use OpenResty::Cache;

    OpenResty::Config->init;
    my $cache = OpenResty::Cache->new;
    $cache->set('key' => 'value'); # use the cache to store (session) data
    $cache->set('key' => 'value', 'trivial'); # pure caching
    print $cache->get('key');  # read the value for the key
    $cache->remove('key');

=head1 DESCRIPTION

This class provides an abstract interface for two caching libraries, L<Cache::FileCache> and L<Cache::Memcached::Fast>.

Which underlying cache library to use depends on the C<cache.type> config option in the F<etc/site_openresty.conf> file.

Note that C<filecache> could eat up your hard disk very quickly. (you'll observe the bloating directory F</tmp/FileCache>.) C<filecache> is only suitable for development; for production use, please use C<memcached> instead (by specifying the C<cache.type> and C<cache.servers> options in F<etc/site_openresty.conf>).

=head1 METHODS

=over

=back

=head1 AUTHOR

Agent Zhang (agentzh) C<< <agentzh@yahoo.cn> >>.

=head1 SEE ALSO

L<OpenResty>, L<Cache::FileCache>, L<Cache::Memcached::Fast>.

_EOC_

        { name => 'team', label => 'Our team', content => <<"_EOC_" },
=head3 Mr Laurie Kan – Founder & General Partner

    China / Hong Kong / 48

Mr Kan has worked for more than 15 years for some of the world’s most successful technology companies, e.g. as Regional Manager for Apple Computers, as Regional Manager for Compaq Computers, as Supervisory Board Director for Packard Bell and as Managing Director for Microsoft in Hong Kong and Southern China. These experiences have endowed him with ample expertise and sharp view as a VC investor around China growth opportunities, esp. in TMT and greentech

For the next 4 years, Mr Kan began to create, invest in and run technology companies. In 1997, he became founder and lead investor in PointCast Asia and meanwhile was COO of China Internet Corporation (now China.com). In 1998, he was responsible for the turnaround of Timeless Software, which later became the 1st company listed on the GEM in HK. In 1999, he established sina.com in HK

Since 1999, Mr Kan has been working in the VC/PE industry.  Initially, in partnership with H&Q Asia Pacific and JH Whitney, he established i100 Corporation, which was listed on the HK Stock Exchange. i100 has invested in a number of wireless and telecom related value added services and software utilities in Hong Kong and China

In 2004, Mr Kan launched ON Capital China Fund and has returned 4.0 times realized + unrealized value for the fund in 3 years, multiplying initial investment principal for all investors

Mr Kan graduated in business from the HK Baptist College and from the Stanford Graduate School of Business Executive Program for Smaller Companies. He is an active participant in the advancement of the IT industry in HK and the PRC, and proactively served on a number of influential committees
_EOC_
        { order => 2, name => 'contact.seller', label => 'Sellers', content => <<"_EOC_" },
=over

=item 1.

I'm B<not> a seller

=item 2.

I'm a very I<good> seller.

=over

=item ABC

=item BCD

=back

=back

Order 2
_EOC_

        { order => 1, name => 'contact.dev', label => 'Developers', content => <<"_EOC_" },
This site was powered by L<http://search.cpan.org/dist/OpenResty|OpenResty> and was developed by agentzh.

If you have any questions regarding the implementation, please send mail to L<mailto:agentzh\@yahoo.cn|my email box>.

Order 1
_EOC_
        { order => 3, name => 'contact.dev', label => 'Developers', content => <<"_EOC_" },

Order 3
_EOC_
        { name => 'contact', label => 'Contact us', content => <<"_EOC_" },
=over

=item Hong Kong office

    F22 Silver Base Center
    Gloucester Road, Central
    Hong Kong
    ph: +852 6880 0198

=item Beijing office

    1419 South Tower
    Kerry Centre 1 Guanghua Road
    Chaoyang District Beijing
    ph: +86 138 1103 9806

=item Shanghai office

    ph: +86 159 2168 1167
    Shenzhen office
    Xin Hua Insurance Tower
    Min Tian Rd, Fu Tian District,

=item Shen Zhen office

    ph: +86 755 8826 4407

=back
_EOC_
    ]
);

$resty->post(
    '/=/view/MenuList',
    { description => 'Menu list', definition => <<'_EOC_' }
select name, label
from Menu
where name ~ '*{1}'
order by display_order asc, $order_by | id asc
_EOC_
);

$resty->post(
    '/=/view/SubMenuList',
    { description => 'Sub Menu list', definition => <<'_EOC_' }
select name, label
from Menu
where name ~ ($parent || '.*{1}') :: lquery
order by display_order asc, $order_by | id asc
_EOC_
);

$resty->post(
    '/=/role/Public/~/~',
    [
        {url => '/=/model/Menu/~/~'},
        {url => '/=/view/MenuList/~/~'},
        {url => '/=/view/SubMenuList/~/~'},
    ]
);

print Dump($resty->get('/=/model')), "\n";

