---
abstract: 'General-purpose web service platform for web applications'
author:
  - 'Agent Zhang <agentzh@yahoo.cn>'
build_requires:
  CGI: 3.33
  Cache::Cache: 1.05
  Class::Prototyped: 0
  HTTP::Response: 1.53
  LWP::UserAgent: 0
  Test::LongString: 0
  Text::Diff: 0
  WWW::OpenResty: 0.06
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: OpenResty
no_index:
  directory:
    - etc
    - tmp
    - demo
    - minisql
    - clients
    - doc
    - t
    - inc
    - t
    - demo
recommends:
  Benchmark::Timer: 0
  HTTP::Server::Simple: 0.27
  Term::ReadLine::Gnu: 0
  Term::ReadLine::Perl: 0
  Text::Diff: 0
  Text::Table: 0
requires:
  CGI::Simple: 1.103
  CGI::Simple::Cookie: 0
  Cache::Memcached::Fast: 0.06
  Clone: 0.22
  Config::Simple: 0
  Cookie::XS: 0.09
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  DBD::Pg: 1.49
  DBI: 1.57
  Data::Structure::Util: 0.15
  Data::UUID: 1.148
  DateTime::Format::Pg: 0
  DateTime::Format::Strptime: 0
  Digest::MD5: 0
  Encode::Guess: 0
  FCGI: 0
  GD::SecurityImage: 1.64
  Hash::Merge: 0
  IPC::Run: 0
  IPC::Run3: 0
  JSON::XS: 2.2
  List::MoreUtils: 0
  List::Util: 0
  MIME::Base64: 0
  Params::Util: 0.22
  Parse::Yapp: 0
  Time::HiRes: 0
  YAML::Syck: 1.04
  perl: 5.6.1
version: 0.3.10
