=head1 NAME

OpenResty::Spec::Install::Apache - Configuring OpenResty.pm with Apache2 + mod_fcgid

=head1 SYNOPSIS

    # File /opt/apache2/conf/httpd.conf
    ...
    LoadModule fcgid_module modules/mod_fcgid.so
    LoadModule rewrite_module modules/mod_rewrite.so
    # the line below is optional:
    LoadModule deflate_module modules/mod_deflate.so
    DocumentRoot "/some/path/to/my/doc/root"
    RewriteEngine on
    RewriteRule ^/=/ /openresty.fcgi [QSA,L]
    AllowEncodedSlashes On
    <Location />
        Options ExecCGI FollowSymLinks
        # the line below is optional:
        AddOutputFilter DEFLATE .fcgi .html .css .js
        AddHandler fcgid-script .fcgi
        Allow from all
    </Location>

    # File /some/path/to/my/doc/root/openresty.fcgi (remember chmod +x this!)
    #!/bin/sh
    exec openresty fastcgi

=head1 DESCRIPTION

OpenResty.pm could be run as a FastCGI application with C<mod_fcgid> or C<mod_fastcgi>. See L</SYNOPSIS> for sample configurations.

Note that when using with C<mod_deflate> to do gzip/deflate compression, it's recommended to set C<frontend.use_gzip> to C<0>.

Apache's C<AllowEncodedSlashes> should be turned on or the following model request would result in a 404 error:

   http://server:1234/=/model/urls/~/http%3A%2F%2Fwww.yahoo.cn%2Fhello%3Fabc%3D32

=head1 AUTHOR

Yichun Zhang (agentzh) C<< <agentzh@gmail.com> >>.

=head1 SEE ALSO

L<OpenResty::Spec::Install::Lighttpd>, L<OpenResty::Spec::Install>, L<OpenResty>.

