#!/usr/bin/env perl

use FindBin;


if( $#ARGV != 0 )
{
	print "usage: $0 <dist_host>\n";
	exit;
}


chdir("$FindBin::Bin/../");
print "svn up ing\n";

chdir("../");
system("svn up");

print "seting revision..";
system("bin/revision.pl");

print "get revision number..";
$rev = `cat revision`;

print "commiting revision..";
system("svn ci -m 'openapi-$rev'");

print "cp -rf trunk openapi-$rev";
print "packing  ...\n";


#system("tar -cz --exclude=trunk/util --exclude=trunk/pkg --exclude=.svn -f  $FindBin::Bin/../pkg/openapi.tgz trunk");

#system("scp $FindBin::Bin/../pkg/openapi.tgz $ARGV[0]:/tmp");

