#!/usr/bin/env perl

use FindBin;


if( $#ARGV < 0 )
{
	print "usage: $0 <dist_host>\n";
	exit;
}


chdir("$FindBin::Bin/../");
print "svn up ing\n";
system("svn up");

print "seting revision..\n";
system("bin/revision.pl\n");

print "get revision number..\n";
$rev = `cat revision`;
$pkgname=$pkgdir="openapi-$rev";

$dist_host=join(",",@ARGV);
print "commiting $rev revision..";
system("svn ci -m 'openapi-$rev packaged and will upload to $dist_host'");

chdir("../");
system("cp -rf trunk openapi-$rev");
system("tar -cz --exclude=$pkgdir/util --exclude=$pkgdir/pkg --exclude=.svn -f  $FindBin::Bin/../pkg/$pkgname.tgz $pkgdir");

foreach (@ARGV)
{
	system("scp -l 10000 $FindBin::Bin/../pkg/$pkgname.tgz $_:/tmp");
}

