#!/usr/bin/env perl

use FindBin;


if( $#ARGV != 0 )
{
	print "usage: $0 <dist_host>\n";
	exit;
}


chdir("$FindBin::Bin/../");
print "svn up ing\n";
system("svn up");

print "seting revision..\n";
system("bin/revision.pl\n");

print "get revision number..\n";
$rev = `cat revision`;
$pkgdir="openapi-$rev";

print "commiting $rev revision..";
system("svn ci -m 'openapi-$rev packed and will upload to $ARGV[0]'");

chdir("../");
system("cp -rf trunk openapi-$rev");
system("tar -cz --exclude=$pkgdir/util --exclude=$pkgdir/pkg --exclude=.svn -f  $FindBin::Bin/../pkg/openapi.tgz $pkgdir");
system("scp $FindBin::Bin/../pkg/openapi.tgz $ARGV[0]:/tmp");

